sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t googleio/docker-reactive -f Dockerfile.dev .

script:
  - docker run -e CI=true googleio/docker-reactive npm run test
